language: cpp
compiler:
  - gcc

before_script:
  - sudo apt-get install -qq libpthread libopengl xlib libxrandr freetype libglew libjpeg libsndfile libopenal
  - cmake .
  - make

notifications:
  email: false
